In [1]:
import pandas as pd
import os

# Load the dataset
os.chdir("..")
data_path = 'datasets'
df = pd.read_csv(os.path.join(data_path, 'wine_quality_1000.csv'))

# Display basic information about the dataset
df.head()

,Unnamed: 0,country,description,points,price,variety
0,87131,US,"Very good Dry Creek Zin, robust and dry and sp...",89,25.0,Zinfandel
1,57952,France,A very herbaceous character makes this wine se...,84,20.0,Bordeaux-style White Blend
2,96046,US,"A little simple and easy, but there's a wealth...",84,19.0,Rosé
3,31920,US,From a dry-farmed vineyard and treated to wild...,88,38.0,Petite Sirah
4,6091,US,"From a site near Annapolis, this wine shows a ...",91,62.0,Pinot Noir

In [2]:
df = df.drop(columns=['Unnamed: 0'])

In [3]:
from nltk.corpus import stopwords
import string
from nltk.stem.wordnet import WordNetLemmatizer
from nltk import word_tokenize

def clean (text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, ' ') # Remove Punctuation
    lowercased = text.lower() # Lower Case
    tokenized = word_tokenize(lowercased) # Tokenize
    words_only = [word for word in tokenized if word.isalpha()] # Remove numbers
    stop_words = set(stopwords.words('english')) # Make stopword list
    without_stopwords = [word for word in words_only if not word in stop_words] # Remove Stop Words
    lemma=WordNetLemmatizer() # Initiate Lemmatizer
    lemmatized = [lemma.lemmatize(word) for word in without_stopwords] # Lemmatize
    cleaned = ' '.join(lemmatized) # Join back to a string
    return cleaned

# Apply to all texts
df['description'] = df.description.apply(clean)
df['variety'] = df.variety.apply(clean)

df.head()

,country,description,points,price,variety
0,US,good dry creek zin robust dry spicy really get...,89,25.0,zinfandel
1,France,herbaceous character make wine seem rather thi...,84,20.0,bordeaux style white blend
2,US,little simple easy wealth raspberry strawberry...,84,19.0,rosé
3,US,dry farmed vineyard treated wild yeast minimal...,88,38.0,petite sirah
4,US,site near annapolis wine show preponderance da...,91,62.0,pinot noir

In [4]:
df.to_csv('datasets/wine_quality_cleaned.csv')